### ISSUE TITLE
Reimbursement for _trader's onion address_

### ISSUE THREAD

**Issue by franz369** [bisq-network/support#1343]
![grafik](https://user-images.githubusercontent.com/125570467/219411134-422e9325-6c96-4928-bd89-6ffa3e988287.png)

Reimbursement for trade MSNQMV-a6dc8212-46a1-4ebf-b264-5949739a6dd3-199

I am BTC buyer as maker for EUR.
Trade amount and asset: 0.8 BTC for 1540 EUR
Deposit amount: 0.0264 BTC

Maker fee tx: e2042b7569605033a5bda8498d47bbc868f819200b46677719daf1e3124608e5
Taker fee tx: 58e33eb311dcbaced4b918bde6a12ef0739907856a2de27fd7227be4254ce2f1
Deposit tx: 049a34065e89342828f7d305f8016ffb6b6472f0f782839161f4c08b194cb0d3
Delayed payout tx: 076200ccaf1ab2c9f863e630974c13377e2e36cd86bed96647b9f4866b4b0807
Payout tx: ed66879d2548bf3e7a062633449d3f5edbc46b6354d1f5e019467dcab616467c

Mediator: pazza83 (6c4cim7h7t3bm4bnchbf727qrhdfrfr6lhod25wjtizm2sifpkktvwad.onion:9999)
Arbitrator: refundagent2 (3z5jnirlccgxzoxc6zwkcgwj66bugvqplzf6z2iyd5oxifiaorhnanqd.onion:9999)

**Reimbursement amount:** 0.00924 BTC / [30 day BSQ average] BSQ x [printing cost] = **`[TOTAL AMOUNT] BSQ`**
Reason for reimbursement: Wrong arbitration decision.

#### Mediation suggestion
Ticket closed on 19 Jan 2023 13:10:23
Mediator node address: 6c4cim7h7t3bm4bnchbf727qrhdfrfr6lhod25wjtizm2sifpkktvwad.onion:9999

Summary:
Trade ID: MSNQMV
Currency: EUR
Reason for dispute: Other
Payout suggestion: BTC seller gets trade amount payout
Trade amount: 0.08 BTC
Payout amount for BTC buyer: 0.0264 BTC
Payout amount for BTC seller: 0.1064 BTC

Summary notes:
BTC buyer sent payment via Revolut but then cancelled payment when if was not accepted by seller
BTC seller confirms no payment received

Trade did not take place. I am proposing trade cancelled and funds returned to traders

-----BEGIN SIGNATURE-----
302c02146763d612b3258a0edf6f6ce221a79aa06d8bd208021473180f28896c1351387c177c6ea6ae90fd839bf9
-----END SIGNATURE-----

Next steps:
Open trade and accept or reject suggestion from mediator

#### Arbitration summary
Arbitration ticket closed with tx: https://mempool.space/tx/ed66879d2548bf3e7a062633449d3f5edbc46b6354d1f5e019467dcab616467c

BTC buyer receives: 0.00924 BTC
BTC seller receives: 0.09716 BTC

The buyer cancelled the transfer after seller did not release BTC on time.  Seller opened arbitration. 1 security deposit not reimbursed as new  arbitration rules were applied: https://github.com/bisq-network/proposals/issues/386

Arbitration secret: usuyg5

Bisq version: v1.9.9

#### Procedure of the trade:

I paid the 1540 EUR at the beginning of the trade period via Revolut and clicked "payment started" in Bisq. After the peer did not react until then, I wrote to him about 40 minutes before the end of the trade period and asked him to finally send the BTC. The trade period expired without the peer reacting. Shortly after the trade period ended, I cancelled the Revolut payment. The complete timeline was:

Purchase time: 14/01/23, 16:12
My payment time: 14/01/23, 16:24 (see screenshot from my Revolut app)
End of the trade period: 15/01/23, 16:12
My cancellation time: 15/01/23, 16:13 (see screenshot from my communication with the Revolut support)

Screenshot from my Revolut app: 
+++ Screenshot removed after confirmation and deletion recommendation of the mediator pazza83 (see below). +++

Screenshot from my communication with the Revolut support: 
+++ Screenshot removed after confirmation and deletion recommendation of the mediator pazza83 (see below). +++

Since the peer did not respond in the given 24 hours trade period, it was my right to cancel my payment after the trade period expired. Later I agreed to the mediator's suggestion to cancel the trade completely and pay out both security deposits in full. Unfortunately, the peer did not agree, which is why the case went to arbitration.

From my security deposit of 0.0264 BTC, the arbitrator unfortunately paid me only 0.1716 BTC. I urge you to pay me the remaining 0.00924 BTC as well. Thank you very much!

**Comment by pazza83** [comment]
@franz369 

Thanks for posting.

Just wanted to confirm that the mediation summary is correct.

I can also confirm your screenshots show the Revolut support agent saying the payment was cancelled successfully around 2023-01-12 at 16:13:48.

For your own and the seller's privacy I would recommend removing the Revolut screen shots.

> Since the peer did not respond in the given 24 hours trade period, it was my right to cancel my payment after the trade period expired. 

I agree you are within your rights to cancel the payment from your account at any point during the trade period. However, by doing so the trade could not be completed (something the seller in this trade confirmed was their preference). Revolut and Interac e-Transfer both allow payments to be cancelled, this is unlike almost all other payment methods in Bisq which are final once sent.

The payment being cancelled is the reason I proposed this trade be cancelled with no penalty to either yourself or the seller. Should this proposal have been accepted by both traders I think this would have been the optimal solution to deal with the cancelled payment.

As the trade went to arbitration the proposal to [not pay out the security deposit of the trade peer to the arbitration case winner](https://github.com/bisq-network/proposals/issues/386) came into effect. This resulted in less funds being available at arbitration than at mediation.

I understand there was a subsequent error with the payout from the arbitrator which I will leave them to comment on.

**Comment by refund-agent2** [comment]
I corrected the wrong initial payout (I switched buyer and seller's penalties, so seller received a higher amount than needed) by paying the amount left  to the buyer in a second [payout](https://mempool.space/tx/d33c38f80aed4ac3f163c9137dda54a16e8fbda89d60430be6b54381e597273e).

> From my security deposit of 0.0264 BTC, the arbitrator unfortunately paid me only 0.1716 BTC. I urge you to pay me the remaining 0.00924 BTC as well. Thank you very much!

This amount already includes the secondary payment. @franz369 is requesting to get the full security deposit, which I don't find a correct arbitration decision for 2 reasons:
- Mediator could not verify if the payment was cancelled after the end of the trading period. I did not have that proof until the arbitration ended, as buyer thought I had access to the trading and mediation chat, and I could have asked for more evidence if I needed it.
- If I would have verified during arbitration that the payment was cancelled after the end of the trading period, I would still have doubts that this the correct procedure as it's very similar to a chargeback. Cancelling a revolut payment should happen only after asking permission to the mediator to do it, after it's evident that seller did something wrong. Probably this would have not entered into arbitration at all if buyer opened mediation at the end of the trading period without cancelling the payment.

So, even though I invited buyer to open this reimbursement request, I already informed that I would oppose to the DAO reimbursement. My decision stands. If I could pay full amounts as with the trading protocol in the past Bisq version, I would have not imposed such high penalties to buyer and seller, but I think that this is a correct payment considering the new rules.

**Comment by franz369** [comment]
I repeat again that I cancelled the Revolut payment only after (!) the end of the trade period. The cancellation time is not an information that could be retrieved in the Revolut app. Since the mediator suggested to cancel the trade completely and pay out the deposits to both peers even without the proof of the cancellation time, I initially waived the proof of the cancellation time and agreed to the mediator's suggestion.

The arbitrator, on the other hand, directly classified me as the culprit, also on the grounds that I could have canceled the payment before the end of the trade period. Thus, I did not even get the chance to prove the cancellation time before the arbitrator's award. I then immediately obtained this proof via Revolut support and delivered it to the arbitrator.

The arbitrator's decision to classify me as the culprit was wrong!

**Comment by pazza83** [comment]
> From my security deposit of 0.0264 BTC, the arbitrator unfortunately paid me only 0.1716 BTC. I urge you to pay me the remaining 0.00924 BTC as well. Thank you very much!

I assume this is a typo?

How much in total was the payout you received from the arbitrator when both payments are added together?

**Comment by franz369** [comment]
> > From my security deposit of 0.0264 BTC, the arbitrator unfortunately paid me only 0.1716 BTC. I urge you to pay me the remaining 0.00924 BTC as well. Thank you very much!
> 
> I assume this is a typo?
> 
> How much in total was the payout you received from the arbitrator when both payments are added together?

The payouts were 0.00924 and 0.00792, which is in sum 0.01716. No typo! Still missing are 0.00924 BTC.

**Comment by pazza83** [comment]
I think you were missing a 0 in your post immediately after the decimal in the total amount received.

You received 0.01716 BTC not 0.1716 BTC as posted above.

I have tried to put all the info together to best follow what happened.

The trade MSNQMV paid out 0.13283040 BTC in the [delayed payout transaction](https://mempool.space/tx/076200ccaf1ab2c9f863e630974c13377e2e36cd86bed96647b9f4866b4b0807)

In the [original payout](https://mempool.space/tx/ed66879d2548bf3e7a062633449d3f5edbc46b6354d1f5e019467dcab616467c) 

BTC buyer received: ‎0.00924000 BTC
‎BTC seller received: 0.09716000 BTC

In the [second payout](https://mempool.space/tx/d33c38f80aed4ac3f163c9137dda54a16e8fbda89d60430be6b54381e597273e)

BTC buyer received: ‎0.00792000 BTC

Therefore totals paid out to BTC buyer and seller were:

BTC buyer received: ‎0.01716000 BTC
‎BTC seller received: 0.09716000 BTC 

Refunded total = 0.11432 BTC

> I corrected the wrong initial payout (I switched buyer and seller's penalties, so seller received a higher amount than needed) by paying the amount left to the buyer in a second [payout](https://mempool.space/tx/d33c38f80aed4ac3f163c9137dda54a16e8fbda89d60430be6b54381e597273e).

@refund-agent2 if you were to do the arbitration summary again with the correct penalties applied what would the payout amount be for the buyer and seller?

**Comment by franz369** [comment]
@pazza83 you are right! Sorry for overlooking the missing 0.

**Comment by refund-agent2** [comment]
@pazza83 https://github.com/bisq-network/roles/issues/93#issuecomment-1438404089
Your numbers are correct. The amount that @franz369 received now is the correct one. The mistake was giving to the BTC seller the amount of the security deposit that corresponded to the BTC buyer, but that was corrected with the second payout.

Buyer would like to receive the full security deposit as he claims that he did nothing wrong. 
I don't think that full reimbursement is correct because buyer cancelled the transfer and provided  proof when arbitration concluded.

**Comment by franz369** [comment]
Thanks @pazza83 for the summary. One important correction: I provided the proof of having paid within the trade period already during the mediation! As a result, the mediator proposed to pay both peers the full security deposit. Only in the arbitration (!) it was objected that the cancellation of my payment could have been made during the trade period. Thereupon, I immediately provided the counter-evidence with the help of Revolut support. Unfortunately, the arbitrator made his decision before this evidence was available.

How could I have known that I also had to prove the cancellation date, if the mediator wanted to pay me the full security deposit even without this proof. The arbitrator, on the other hand, obviously considered this receipt essential without requesting it from me.

**Comment by franz369** [comment]
Hi @pazza83, can you please help me understand the current status of this issue. Will I get my full security deposit refunded? Above, leo816 has joined the communication. Is there any response or action expected from me?

**Comment by pazza83** [comment]
Hi @franz369 

The issue is still active.

@refund-agent2 commented:

> So, even though I invited buyer to open this reimbursement request, I already informed that I would oppose to the DAO reimbursement. My decision stands. If I could pay full amounts as with the trading protocol in the past Bisq version, I would have not imposed such high penalties to buyer and seller, but I think that this is a correct payment considering the new rules.

I agree with @refund-agent2. I think you have been reimbursed for this trade in line with how reimbursement works for trades post 1st Jan 2023.

Doing the sums with the amounts:

**Total available for arbitration as per https://github.com/bisq-network/proposals/issues/386** 

Trade amount: 0.08 BTC
One security deposit: 0.0264 BTC

= **0.1064 BTC**

**Total refunded by arbitrator:**

BTC buyer received: ‎0.01716000 BTC
‎BTC seller received: 0.09716000 BTC

**Refunded total = 0.11432 BTC**

I can see why you consider this unfortunate but as the arbitrator can only make payout using only the trade amount and one security deposit it means there is less BTC available at arbitration than at mediation.

Effectively the arbitrator is forced to 'split' the one security deposit between both the buyer and seller. Both the buyer and seller lost out on this trade with both of them receiving less BTC than they entered the trade with. This is a result of the proposal [to not pay out the security deposit of the trade peer to the arbitration case winner](https://github.com/bisq-network/proposals/issues/386).
 
Should you wish to claim reimbursement from the DAO you can ask the DAO to vote on your reimbursement request. If you would like to do so please comment below and I or @refund-agent2 will provide you further instructions. See the wiki here for more info: https://bisq.wiki/Making_a_reimbursement_request

**Comment by franz369** [comment]
Hello @refund-agent2, @pazza83, this arbitration has been going on for four months now. Is it still in progress? Can I expect a result soon?

**Comment by refund-agent2** [comment]
I still consider that this payment was correct, and there are no voices supporting your view, so I think that the best is to let it go.
You can submit this to a DAO voting, but it's unlikely to be approved.

**Comment by franz369** [comment]
@refund-agent2: Again, I cancelled the payment after (!) the trade period had ended and the peer had not paid the BTC. I have also proved this! If I am penalized for this, this is tantamount to theft of my money. This is not acceptable!

**Comment by pazza83** [comment]
Hi @franz369 

If you would like to put your reimbursement request to a Bisq DAO vote you can do so.

You can submit your reimbursement request in the Bisq app and post your transaction ID here. That will mean that their will be vote by the DAO to approve or reject the reimbursement.

See instructions here: 
https://bisq.wiki/Making_a_reimbursement_request#Submit_your_reimbursement_request_to_the_Bisq_DAO
