### ISSUE TITLE
Fee reimbursement for trade fukfcgjg

### ISSUE THREAD

**Issue by dav1dpgit** [bisq-network/support#567]
>_The XXXXX part in the issue title are the first characters of the Trade ID before the "-" (dash)._

SCREENSHOT HERE
![image](https://user-images.githubusercontent.com/60247151/100398683-18d6fb00-3093-11eb-8691-2cb79adc477a.png)

>_The screenshot from the Bisq client must have the **Trade ID**, **Deposit**, **Maker** and **Taker** TXIDs visible. Of course some trades do not have all 3 types, that is ok. Make sure all private information is covered (like bank accounts, name, etc). **Do not upload images where sensitive private data is visible!**_

Maker:  cfbce12510aa02ceaf7b668e3bef99a902af7bf30abd8a7d5153d6a4cbd2b96f
Taker: N/A
Deposit: N/A

>_A reimbursement request has to contain textual representation of **Maker**, **Taker** and **Deposit** TXIDs (copy them from the client to the issue). **All TXIDs that are visible in the screenshot must be copied to the issue in text form! Please use exact form for Maker/Taker/Deposit - no abbreviations like M:, T: or adding extra characters like "Maker TX:", etc. Leave those fields as they are and replace the "........" with the appropreate txid**_

Bisq version: 1.5.0

>_Provide the Bisq client version to help developers identify the causing issue._

Other notes:

Looking to receive my transaction BSQ fee back.

**Comment by jmacxx** [comment]
This issue is fixed by https://github.com/bisq-network/bisq/pull/4764 which will be in the next release, [1.5.1](https://github.com/bisq-network/bisq/milestone/45?closed=1)


@dav1dpgit  it looks like the your wallet is not synced properly.

**Comment by dav1dpgit** [comment]
Thanks James.  How would one go about syncing the wallet to fix the issue?

**Comment by jmacxx** [comment]
First, see if a restart of the Bisq app causes it to sync up.  I always look at DAO -> BSQ Wallet -> Transactions and watch for the progress bar and `latest verified block` displayed there to catch up to [mempool.space](https://mempool.space).


If it still does not sync then you probably want to do an [SPV Resync](https://bisq.wiki/Resyncing_SPV_file)

**Comment by dav1dpgit** [comment]
Thanks.  Just resetting the app did the trick.

Will I still get my BSQ back?

**Comment by jmacxx** [comment]
Yes there's a process this ticket will go through to get your fees back.  @leo816 will contact you here.

**Comment by leo816** [comment]
please provide the btc address where you would like to be reimbursed

**Comment by dav1dpgit** [comment]
> please provide the btc address where you would like to be reimbursed

bc1qxqjay5rrjygsgcyu8gwh2ytk9f4dlmendag3mk

Thank you very much.

**Comment by dav1dpgit** [comment]
If you are looking for a BSQ address, use this one:

B16ssKC5Fh2QaFip9NBzWYfZdA2xKsRidjY

**Comment by dav1dpgit** [comment]
@leo816 When will this reimbursement be made?

**Comment by leo816** [comment]
there has been an issue and we are trying to solve it asap

**Comment by leo816** [comment]
Closing as reimbursed via the batch transaction documented at https://github.com/bisq-network/support/issues/576#issuecomment-749487833
